# Generated by Django 4.0.6 on 2022-07-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('lower_rate', models.FloatField(blank=True)),
                ('upper_rate', models.FloatField(blank=True)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
