# Generated by Django 4.0.6 on 2022-07-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_company_joboffer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
