# Generated by Django 4.0.6 on 2022-07-27 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
